version: '3.8'

services:
  kvstore1:
    build: .
    ports:
      - "6379:6379"
    volumes:
      - kvstore_data1:/app/data
      - kvstore_logs1:/app/logs
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:+UseG1GC
    networks:
      - redis_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "echo", "PING", "|", "nc", "localhost", "6379"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  kvstore2:
    build: .
    ports:
      - "6380:6379"
    volumes:
      - kvstore_data2:/app/data
      - kvstore_logs2:/app/logs
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:+UseG1GC
    networks:
      - redis_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "echo", "PING", "|", "nc", "localhost", "6379"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  haproxy:
    image: haproxy:2.7
    ports:
      - "6378:6378"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - redis_net
    depends_on:
      kvstore1:
        condition: service_healthy
      kvstore2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "PING", "|", "nc", "localhost", "6378"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  redis_net:
    driver: bridge

volumes:
  kvstore_data1:
  kvstore_logs1:
  kvstore_data2:
  kvstore_logs2: 